apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: alecigolini/fiap-techchallengeapipedidoproduto:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://techchallenge-dev.postgres.database.azure.com:5432/postgres
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_PASSWORD
            - name: CLIENT_MERCADO_PAGO_USER_ID
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MP_USER_ID
            - name: CLIENT_MERCADO_PAGO_POS_ID
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MP_POS_ID
            - name: CLIENT_MERCADO_PAGO_EXTERNAL_STORE_ID
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MP_EXTERNAL_STORE_ID
            - name: CLIENT_MERCADO_PAGO_EXTERNAL_POS_ID
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MP_EXTERNAL_POS_ID
            - name: CLIENT_MERCADO_PAGO_AUTH_HEADER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MP_AUTH_HEADER
          resources:
            requests:
              cpu: "400m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: java-app
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: java-app
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-app
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: java-app
                port:
                  number: 80
  tls:
    - hosts:
        - techchallenge.app.br
      secretName: meu-certificado-tls
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: java-app-hpa
  namespace: default
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind:  Deployment
    name: java-app
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          periodSeconds: 15
          value: 1
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          periodSeconds: 60
          value: 1