name: Application Deployment Kubernetes

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  kubernetes:
    name: Run Kubernetes
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t alecigolini/fiap-techchallengeapipedidoproduto:latest .

      - name: Push Docker image
        run: docker push alecigolini/fiap-techchallengeapipedidoproduto:latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group rg-fiap \
            --name k8s-fiap-dev
          
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./kubernetes/ --recursive


